### ISSUE TITLE
项目是不是代码没传好？

### ISSUE THREAD

**Issue by aesean** [hongyangAndroid/ChangeSkin#6]
我clone代码后无法编译，修改build.gradle的插件加载顺序修改了插件版本为最新版本后，drawable中有个文件名大写了，修改文件名后可以构建了。
（ classpath 'com.android.tools.build:gradle:1.5.0'
 classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
 classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.0'）。
然后就是第三个item和插件式换肤无效果。

**Comment by hongyangAndroid** [comment]
不好意思哈，重新上传了一下项目，之前不知道为什么有个资源文件名称大写了。

恩，对于6.0，我暂时没用做处理，主要由于需要读取sdcard的权限，目前你可以安装了，通过settings->app->SkinChangeNow然后把Storage的权限开启，再进行测试就好了。

后面有时间会对6.0的权限做一下处理，多谢反馈~
